---
title: "Rikuchiy Llacta"
---

Encontrar치 contenido sobre algunas enfermedades que afectan a los pueblos de la Amazon칤a y los Andes y la poblaci칩n afroperuana en el Per칰, en qu칠 proporci칩n por sexo, cu치les son las edades m치s afectadas, en qu칠 departamentos se dan los casos, y otros aspectos que influencian en la salud de las personas.

### Reportes Disponibles

### **Salud intercultural**
::::: grid
::: g-col-6
### 游늵 [Hepatitis B en poblaciones originarias amaz칩nicas](hepatitis_b.html)

**Fecha:** Marzo 2024 
**Datos:** HISS MINSA.
:::

::: {.g-col-6}
### 游늵 [Tuberculosis, un desaf칤o en las poblaciones ind칤genas y afroperuanas](tuberculosis.html)
**Fecha:** Diciembre 2025 
**Datos:** HISS MINSA. 

:::

::: {.g-col-6}
### 游빍 [Desnutrici칩n en poblaciones de la Amazon칤a, Andes y Afroperuana](desnutricion.html)
**Fecha:** Mayo 2022
**Datos:** HISS MINSA 
:::

::: {.g-col-6}
### 游뽘 [VIH en las poblaciones amaz칩nicas, andinas y afroperuanas](VIH.html)
**Fecha:** Diciembre 2025
**Datos:** HISS MINSA 
:::

::: {.g-col-6}
### 游눪 [Anemia nutricional en la poblaci칩n afroperuana y en etnias andinas y amaz칩nicas](anemia.html)
**Fecha:** Marzo 2024
**Datos:** HISS MINSA

:::

::: {.g-col-6}
### 游꼝 [Hipertensi칩n, asesino silencioso que amenaza a poblaciones ind칤genas y afroperuanas](hipertension.html)
**Fecha:** Diciembre 2025
**Datos:** HISS MINSA 
:::

::: {.g-col-6}
### 游뽘 [Dengue](dengue.html)
**Fecha:** Diciembre 2025
**Datos:** HISS MINSA
:::

::: {.g-col-6}
### 游꺔 [VIH en poblaci칩n yanesha](VIH_yanesha.html)
**Fecha:** Mayo 2023
**Datos:** HISS MINSA 

:::

::: {.g-col-6}
### 游꺔 [Cambio Clim치tico](cambio_climatico.html)
**Fecha:** Mayo 2023
**Datos:** Servicio Nacional de Meteorolog칤a e Hidrolog칤a (SENAMHI).
:::

::: {.g-col-6}
### 游꺔 [Obesidad](obesidad.html)
**Fecha:** Diciembre 2025
**Datos:** Scopus 
Un an치lisis completo de la producci칩n cient칤fica global sobre la especie vegetal Uncaria tomentosa (U침a de gato), incluyendo tendencias temporales, mapas de colaboraci칩n y nubes de palabras clave. 
:::

:::::

### **Investigaci칩n Social: Etnicidad**
::::: grid
::: {.g-col-6}
### 游꺔 [Fallecidos por etnicidad](Produccion_cientifica_coca.html)
**Fecha:** Diciembre 2025
**Datos:** Scopus 
Un an치lisis completo de la producci칩n cient칤fica global sobre la especie vegetal Erythroxylum coca (coca), incluyendo tendencias temporales, mapas de colaboraci칩n y nubes de palabras clave.
:::

::: {.g-col-6}
### 游꺔 [Atendidos por pertinencia 칠tnica](Produccion_cientifica_ayahuasca.html)
**Fecha:** Diciembre 2025
**Datos:** Scopus 
Un an치lisis completo de la producci칩n cient칤fica global sobre el brebaje de Banisteriopsis caapi y Psychotria viridis (Ayahuasca), incluyendo tendencias temporales, mapas de colaboraci칩n y nubes de palabras clave.
:::

::: {.g-col-6}
### 游꺔 [Atenciones por etnicidad](Produccion_cientifica_sacha_inchi.html)
**Fecha:** Diciembre 2025
**Datos:** Scopus 
Un an치lisis completo de la producci칩n cient칤fica global sobre la especie vegetal Plukenetia volubilis (Sacha Inchi), incluyendo tendencias temporales, mapas de colaboraci칩n y nubes de palabras clave. 

:::

::: {.g-col-6}
### 游꺔 [Enfermedades en poblaciones indigenas y afro](Produccion_cientifica_maca.html)
**Fecha:** Diciembre 2025
**Datos:** Scopus 
Un an치lisis completo de la producci칩n cient칤fica global sobre la especie vegetal Lepidium meyenii (Maca), incluyendo tendencias temporales, mapas de colaboraci칩n y nubes de palabras clave. 
:::



::: {.g-col-6}
### 游꺔 [Mortalidad materna por etnicidad](Produccion_cientifica_una_de_gato.html)
**Fecha:** Diciembre 2025
**Datos:** Scopus 
Un an치lisis completo de la producci칩n cient칤fica global sobre la especie vegetal Uncaria tomentosa (U침a de gato), incluyendo tendencias temporales, mapas de colaboraci칩n y nubes de palabras clave. 
:::

:::::
